config/routes.rb
Rails.application.routes.draw do
  root 'food_logs#index'
  resources :food_logs

end

app/models/food_log.rb
class FoodLog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/food_logs_controller.rb
class FoodLogsController < ApplicationController
  before_action :set_food_log, only: [:show, :edit, :update, :destroy]

  # GET /food_logs
  # GET /food_logs.json
  def index
    @food_logs = FoodLog.all
  end

  # GET /food_logs/1
  # GET /food_logs/1.json
  def show
  end

  # GET /food_logs/new
  def new
    @food_log = FoodLog.new
  end

  # GET /food_logs/1/edit
  def edit
  end

  # POST /food_logs
  # POST /food_logs.json
  def create
    @food_log = FoodLog.new(food_log_params)

    respond_to do |format|
      if @food_log.save
        format.html { redirect_to @food_log, notice: 'Log submission was successfully created.' }
        format.json { render :show, status: :created, location: @food_log }
      else
        format.html { render :new }
        format.json { render json: @food_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_logs/1
  # PATCH/PUT /food_logs/1.json
  def update
    respond_to do |format|
      if @food_log.update(food_log_params)
        format.html { redirect_to @food_log, notice: 'Log submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_log }
      else
        format.html { render :edit }
        format.json { render json: @food_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_logs/1
  # DELETE /food_logs/1.json
  def destroy
    @food_log.destroy
    respond_to do |format|
      format.html { redirect_to food_logs_url, notice: 'Food log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_log
      @food_log = FoodLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_log_params
      params.require(:food_log).permit(:name, :entry, :calories, :protein, :carbs, :fat, :weight)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_logs_helper.rb
module FoodLogsHelper
end

app/views/food_logs/_form.html.erb
<%= form_for(@food_log) do |f| %>
  <% if @food_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_log.errors.count, "error") %> prohibited this food_log from being saved:</h2>

      <ul>
      <% @food_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, 'Your Name' %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :entry, 'Food Item, Description' %><br>
    <%= f.text_area :entry, class:'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :calories, 'Calories' %><br>
    <%= f.number_field :calories, class:'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :protein, 'Protein (Grams)' %><br>
    <%= f.number_field :protein, class:'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :carbs, 'Carbs (Grams)' %><br>
    <%= f.number_field :carbs, class:'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :fat,'Fat (Grams)' %><br>
    <%= f.number_field :fat, class:'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :weight,'Weight (Grams)' %><br>
    <%= f.text_field :weight, class:'form-control' %>
  </div>
  <div class="actions form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_logs/edit.html.erb
<h1>Editing Food Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_log %> |
<%= link_to 'Back', food_logs_path %>

app/views/food_logs/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Food Item</th>
      <th>Calories</th>
      <th>Protein(grams)</th>
      <th>Carbs(grams)</th>
      <th>Fat(grams)</th>
      <th>Weight(grams)</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_logs.each do |food_log| %>
      <tr>
        <td><%= food_log.name %></td>
        <td><%= food_log.entry %></td>
        <td><%= food_log.calories %></td>
        <td><%= food_log.protein %></td>
        <td><%= food_log.carbs %></td>
        <td><%= food_log.fat %></td>
        <td><%= food_log.weight %></td>
        <td><%= food_log.created_at.to_time %></td>
        <td><%= link_to 'Show', food_log, class: 'btn btn-info' %></td>
        <td><%= link_to 'Edit', edit_food_log_path(food_log), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Delete', food_log, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food log', new_food_log_path, class: 'btn btn-primary' %>

app/views/food_logs/new.html.erb
<h1>New Food Log</h1>

<%= render 'form' %>

<%= link_to 'Back', food_logs_path %>

app/views/food_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_log.name %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @food_log.entry %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @food_log.calories %>
</p>

<p>
  <strong>Protein:</strong>
  <%= @food_log.protein %>
</p>

<p>
  <strong>Carbs:</strong>
  <%= @food_log.carbs %>
</p>

<p>
  <strong>Fat:</strong>
  <%= @food_log.fat %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @food_log.weight %>
</p>

<%= link_to 'Edit', edit_food_log_path(@food_log) %> |
<%= link_to 'Back', food_logs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mana Food Log</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="jumbotron site-header">
  <div class="container text-center">
    <h1>Mana Food Log</h1>
  </div>
</header>
<div class="container">
  <%= yield %>
</div>
</body>
</html>